# docker build -t angpassauth .
# docker login
# docker tag expassauth tumbone/angpassauth
# docker push tumbone/angpassauth
# docker run -p 3001:3001 tumbone/angpassauth

# docker machine env myvm1
# & "C:\Program Files\Docker\Docker\Resources\bin\docker-machine.exe" env myvm1 | Invoke-Expression
# docker swarm init
# docker stack deploy -c docker-compose.yml node-express-auth-app 

version: "3"
services:
  angpassauth:
    image: tumbone/angpassauth:latest
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3001:3001"
    networks:
      - webnet
  expassauth:
    image: tumbone/expassauth:latest
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports: 
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  mongodb:
    image: mongo
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: